### ISSUE TITLE
Add unit tests for package

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/gh-openapi-docs#6]
Mocha seems like a reasonable choice, but I don't have any strong preferences.

**Comment by jb-adams** [comment]
Hi @jaeddy , what's the status of this? If unit testing hasn't been incorporated yet, I can add `mocha` testing. I can also take a stab at #7 and set up Travis CI + code coverage in the same PR.
Let me know if this is already being tackled, don't want to duplicate efforts.
Thanks!

**Comment by jaeddy** [comment]
Hey @jb-adams — nobody has started on this, to my knowledge. That would be awesome — thanks!

**Comment by jb-adams** [comment]
awesome, will do!

I'm encountering a runtime error when building on Travis CI only, which is causing the build to fail. It looks like the information from `git-repo-info` inside `src/lib/environment.js` is not loading correctly in Travis.

**Travis:**
```
{ sha: '98e67888f6d2d60ee2e46ee058a02a55344b593f',
  abbreviatedSha: '98e67888f6',
  branch: undefined,
  tag: null,
  committer: null,
  committerDate: null,
  author: null,
  authorDate: null,
  commitMessage: null,
  root: '/home/travis/build/jb-adams/gh-openapi-docs',
  commonGitDir: '/home/travis/build/jb-adams/gh-openapi-docs/.git',
  worktreeGitDir: '/home/travis/build/jb-adams/gh-openapi-docs/.git',
  lastTag: null,
  commitsSinceLastTag: Infinity }
 RUNTIME EXCEPTION  Exception occurred while loading your tests
```

**Local:**
```
{ sha: '98e67888f6d2d60ee2e46ee058a02a55344b593f',
  abbreviatedSha: '98e67888f6',
  branch: 'feature/unit-testing',
  tag: null,
  committer: 'Jeremy Adams <jeremy.adams@ga4gh.org>',
  committerDate: '2020-05-21T19:03:01.000Z',
  author: 'Jeremy Adams <jeremy.adams@ga4gh.org>',
  authorDate: '2020-05-21T19:03:01.000Z',
  commitMessage:
   'temporarily removed global installs from travis.yml, mocha testing',
  root: '/Users/jadams/Github/jb-adams/gh-openapi-docs',
  commonGitDir: '/Users/jadams/Github/jb-adams/gh-openapi-docs/.git',
  worktreeGitDir: '/Users/jadams/Github/jb-adams/gh-openapi-docs/.git',
  lastTag: null,
  commitsSinceLastTag: Infinity,
  parents: [ '13cd43ec549eacfda283a54dd8c92473288ef367' ] }
```

Specifically this is causing an `undefined` exception in the `toLowerCase` method in `src/lib/config.js`

Are the null fields in the Travis build repo info expected behavior? Or is there something else I need to configure?

**Comment by jb-adams** [comment]
This is being caused by the `git checkout` command in the Travis build steps. eg:
```
git clone --depth=50 --branch=feature/unit-testing https://github.com/jb-adams/gh-openapi-docs.git jb-adams/gh-openapi-docs
cd jb-adams/gh-openapi-docs
git checkout -qf 98e67888f6d2d60ee2e46ee058a02a55344b593f # this command
```

`git checkout` prevents the correct branch info from being loaded from the `.git` folder via the `git-repo-info` library. But resetting the branch to `git checkout $BRANCH_NAME` enables the branch info to be loaded properly, and lets unit testing complete normally.

Maybe need to add a command to `before_script` to do this before running unit tests.
